import { Component } from '@angular/core';
import { Nationality } from '@ww2/shared/nationality';
import { UnitType } from '@ww2/shared/unit-type';
import { Battalion } from '../battalion/battalion';
import { MilitaryUnit } from '@ww2/shared/military-unit';
import { UpperCasePipe } from '@angular/common';
import {
  AircraftCarrierCombatant,
  AntiAirCombatant,
  ArtilleryCombatant,
  BattleshipCombatant,
  BomberCombatant,
  DestroyerCombatant,
  FighterJetCombatant,
  InfantryCombatant,
  SubmarineCombatant,
  TankCombatant,
  TransportCombatant,
} from '../combatant';

@Component({
  selector: 'ww2-battle-board',
  imports: [Battalion, UpperCasePipe],
  templateUrl: './battle-board.html',
  styleUrl: './battle-board.scss',
  host: {
    class: 'battle-board',
  },
})
export class BattleBoard {
  UnitType = UnitType;
  Nationality = Nationality;

  protected attackers: MilitaryUnit[] = [
    // Infantry units
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.UNITED_STATES,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.UNITED_STATES,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.SOVIET_UNION,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.SOVIET_UNION,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,

    // Artillery units
    {
      type: UnitType.ARTILLERY,
      nationality: Nationality.UNITED_STATES,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as ArtilleryCombatant,
    {
      type: UnitType.ARTILLERY,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as ArtilleryCombatant,
    {
      type: UnitType.ARTILLERY,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as ArtilleryCombatant,
    {
      type: UnitType.ARTILLERY,
      nationality: Nationality.SOVIET_UNION,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as ArtilleryCombatant,

    // Tank units
    {
      type: UnitType.TANK,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TankCombatant,
    {
      type: UnitType.TANK,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TankCombatant,
    {
      type: UnitType.TANK,
      nationality: Nationality.UNITED_STATES,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TankCombatant,
    {
      type: UnitType.TANK,
      nationality: Nationality.UNITED_STATES,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TankCombatant,
    {
      type: UnitType.TANK,
      nationality: Nationality.SOVIET_UNION,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TankCombatant,
    {
      type: UnitType.TANK,
      nationality: Nationality.SOVIET_UNION,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TankCombatant,
    {
      type: UnitType.TANK,
      nationality: Nationality.SOVIET_UNION,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TankCombatant,

    // Fighter jet units
    {
      type: UnitType.FIGHTER_JET,
      nationality: Nationality.UNITED_STATES,
      attack: 3,
      defense: 4,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as FighterJetCombatant,
    {
      type: UnitType.FIGHTER_JET,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 3,
      defense: 4,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as FighterJetCombatant,
    {
      type: UnitType.FIGHTER_JET,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 3,
      defense: 4,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as FighterJetCombatant,
    {
      type: UnitType.FIGHTER_JET,
      nationality: Nationality.SOVIET_UNION,
      attack: 3,
      defense: 4,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as FighterJetCombatant,
    {
      type: UnitType.FIGHTER_JET,
      nationality: Nationality.SOVIET_UNION,
      attack: 3,
      defense: 4,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as FighterJetCombatant,

    // Bomber units
    {
      type: UnitType.BOMBER,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 4,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as BomberCombatant,
    {
      type: UnitType.BOMBER,
      nationality: Nationality.UNITED_STATES,
      attack: 4,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as BomberCombatant,
    {
      type: UnitType.BOMBER,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 4,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as BomberCombatant,

    // Battleship units
    {
      type: UnitType.BATTLESHIP,
      nationality: Nationality.UNITED_STATES,
      attack: 4,
      defense: 4,
      hitPoints: 2,
      remainingHitPoints: 2,
    } as BattleshipCombatant,
    {
      type: UnitType.BATTLESHIP,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 4,
      defense: 4,
      hitPoints: 2,
      remainingHitPoints: 2,
    } as BattleshipCombatant,
    {
      type: UnitType.BATTLESHIP,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 4,
      defense: 4,
      hitPoints: 2,
      remainingHitPoints: 2,
    } as BattleshipCombatant,

    // Destroyer units
    {
      type: UnitType.DESTROYER,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as DestroyerCombatant,
    {
      type: UnitType.DESTROYER,
      nationality: Nationality.UNITED_STATES,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as DestroyerCombatant,
    {
      type: UnitType.DESTROYER,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as DestroyerCombatant,
    {
      type: UnitType.DESTROYER,
      nationality: Nationality.SOVIET_UNION,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as DestroyerCombatant,

    // Aircraft carrier units
    {
      type: UnitType.AIRCRAFT_CARRIER,
      nationality: Nationality.UNITED_STATES,
      attack: 1,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as AircraftCarrierCombatant,
    {
      type: UnitType.AIRCRAFT_CARRIER,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 1,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as AircraftCarrierCombatant,

    // Transport units
    {
      type: UnitType.TRANSPORT,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 0,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TransportCombatant,
    {
      type: UnitType.TRANSPORT,
      nationality: Nationality.UNITED_STATES,
      attack: 0,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TransportCombatant,
    {
      type: UnitType.TRANSPORT,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 0,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TransportCombatant,

    // Submarine units
    {
      type: UnitType.SUBMARINE,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as SubmarineCombatant,
    {
      type: UnitType.SUBMARINE,
      nationality: Nationality.UNITED_STATES,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as SubmarineCombatant,
    {
      type: UnitType.SUBMARINE,
      nationality: Nationality.UNITED_KINGDOM,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as SubmarineCombatant,
    {
      type: UnitType.SUBMARINE,
      nationality: Nationality.SOVIET_UNION,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as SubmarineCombatant,
  ];

  protected defenders: MilitaryUnit[] = [
    // Infantry units
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.GERMANY,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.JAPAN,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.GERMANY,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.JAPAN,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.GERMANY,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.JAPAN,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,
    {
      type: UnitType.INFANTRY,
      nationality: Nationality.GERMANY,
      attack: 1,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as InfantryCombatant,

    // Artillery units
    {
      type: UnitType.ARTILLERY,
      nationality: Nationality.GERMANY,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as ArtilleryCombatant,
    {
      type: UnitType.ARTILLERY,
      nationality: Nationality.JAPAN,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as ArtilleryCombatant,
    {
      type: UnitType.ARTILLERY,
      nationality: Nationality.GERMANY,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as ArtilleryCombatant,
    {
      type: UnitType.ARTILLERY,
      nationality: Nationality.JAPAN,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as ArtilleryCombatant,

    // Tank units
    {
      type: UnitType.TANK,
      nationality: Nationality.GERMANY,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TankCombatant,
    {
      type: UnitType.TANK,
      nationality: Nationality.JAPAN,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TankCombatant,
    {
      type: UnitType.TANK,
      nationality: Nationality.GERMANY,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TankCombatant,
    {
      type: UnitType.TANK,
      nationality: Nationality.JAPAN,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TankCombatant,
    {
      type: UnitType.TANK,
      nationality: Nationality.GERMANY,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TankCombatant,

    // Anti-air units
    {
      type: UnitType.ANTI_AIR_GUN,
      nationality: Nationality.GERMANY,
      attack: 0,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as AntiAirCombatant,
    {
      type: UnitType.ANTI_AIR_GUN,
      nationality: Nationality.GERMANY,
      attack: 0,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as AntiAirCombatant,

    // Fighter jet units
    {
      type: UnitType.FIGHTER_JET,
      nationality: Nationality.GERMANY,
      attack: 3,
      defense: 4,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as FighterJetCombatant,
    {
      type: UnitType.FIGHTER_JET,
      nationality: Nationality.JAPAN,
      attack: 3,
      defense: 4,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as FighterJetCombatant,
    {
      type: UnitType.FIGHTER_JET,
      nationality: Nationality.GERMANY,
      attack: 3,
      defense: 4,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as FighterJetCombatant,
    {
      type: UnitType.FIGHTER_JET,
      nationality: Nationality.JAPAN,
      attack: 3,
      defense: 4,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as FighterJetCombatant,

    // Bomber units
    {
      type: UnitType.BOMBER,
      nationality: Nationality.GERMANY,
      attack: 4,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as BomberCombatant,
    {
      type: UnitType.BOMBER,
      nationality: Nationality.JAPAN,
      attack: 4,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as BomberCombatant,
    {
      type: UnitType.BOMBER,
      nationality: Nationality.GERMANY,
      attack: 4,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as BomberCombatant,
    {
      type: UnitType.BOMBER,
      nationality: Nationality.JAPAN,
      attack: 4,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as BomberCombatant,

    // Battleship units
    {
      type: UnitType.BATTLESHIP,
      nationality: Nationality.GERMANY,
      attack: 4,
      defense: 4,
      hitPoints: 2,
      remainingHitPoints: 2,
    } as BattleshipCombatant,
    {
      type: UnitType.BATTLESHIP,
      nationality: Nationality.JAPAN,
      attack: 4,
      defense: 4,
      hitPoints: 2,
      remainingHitPoints: 2,
    } as BattleshipCombatant,
    {
      type: UnitType.BATTLESHIP,
      nationality: Nationality.GERMANY,
      attack: 4,
      defense: 4,
      hitPoints: 2,
      remainingHitPoints: 2,
    } as BattleshipCombatant,

    // Destroyer units
    {
      type: UnitType.DESTROYER,
      nationality: Nationality.GERMANY,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as DestroyerCombatant,
    {
      type: UnitType.DESTROYER,
      nationality: Nationality.JAPAN,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as DestroyerCombatant,
    {
      type: UnitType.DESTROYER,
      nationality: Nationality.GERMANY,
      attack: 3,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as DestroyerCombatant,

    // Aircraft carrier units
    {
      type: UnitType.AIRCRAFT_CARRIER,
      nationality: Nationality.JAPAN,
      attack: 1,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as AircraftCarrierCombatant,
    {
      type: UnitType.AIRCRAFT_CARRIER,
      nationality: Nationality.GERMANY,
      attack: 1,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as AircraftCarrierCombatant,
    {
      type: UnitType.AIRCRAFT_CARRIER,
      nationality: Nationality.JAPAN,
      attack: 1,
      defense: 3,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as AircraftCarrierCombatant,

    // Transport units
    {
      type: UnitType.TRANSPORT,
      nationality: Nationality.GERMANY,
      attack: 0,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TransportCombatant,
    {
      type: UnitType.TRANSPORT,
      nationality: Nationality.JAPAN,
      attack: 0,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TransportCombatant,
    {
      type: UnitType.TRANSPORT,
      nationality: Nationality.GERMANY,
      attack: 0,
      defense: 1,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as TransportCombatant,

    // Submarine units
    {
      type: UnitType.SUBMARINE,
      nationality: Nationality.GERMANY,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as SubmarineCombatant,
    {
      type: UnitType.SUBMARINE,
      nationality: Nationality.JAPAN,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as SubmarineCombatant,
    {
      type: UnitType.SUBMARINE,
      nationality: Nationality.GERMANY,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as SubmarineCombatant,
    {
      type: UnitType.SUBMARINE,
      nationality: Nationality.JAPAN,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as SubmarineCombatant,
    {
      type: UnitType.SUBMARINE,
      nationality: Nationality.GERMANY,
      attack: 2,
      defense: 2,
      hitPoints: 1,
      remainingHitPoints: 1,
    } as SubmarineCombatant,
  ];
}
