import type { TerritoryName } from './territory-names';

export type SpecialAdjacencyKind = 'canal';

export interface SpecialAdjacency {
  readonly kind: SpecialAdjacencyKind;
  readonly territories: readonly [TerritoryName, TerritoryName];
  readonly requiredTerritories: readonly TerritoryName[];
}

export const ADJACENT_TERRITORIES_BY_NAME: Record<TerritoryName, readonly TerritoryName[]> = {
  Alaska: ['Sea Zone 63', 'Sea Zone 64', 'Western Canada'],
  Algeria: ['Libya', 'Sea Zone 12', 'Sea Zone 13', 'Sea Zone 14'],
  'Anglo-Egypt': [
    'Belgian Congo',
    'French Equatorial Africa',
    'Italian East Africa',
    'Libya',
    'Sea Zone 14',
    'Sea Zone 15',
    'Sea Zone 34',
    'Trans-Jordan',
  ],
  Archangel: ['Karelia S.S.R.', 'Russia', 'Sea Zone 4', 'West Russia'],
  Australia: ['Sea Zone 38', 'Sea Zone 39', 'Sea Zone 40', 'Sea Zone 46'],
  Balkans: ['Eastern Europe', 'Germany', 'Sea Zone 16', 'Southern Europe', 'Ukraine S.S.R.'],
  'Belgian Congo': [
    'Anglo-Egypt',
    'French Equatorial Africa',
    'Italian East Africa',
    'Rhodesia',
    'Sea Zone 23',
  ],
  Belorussia: ['Eastern Europe', 'Karelia S.S.R.', 'Ukraine S.S.R.', 'West Russia'],
  Borneo: ['Sea Zone 48'],
  Brazil: ['Sea Zone 18', 'Sea Zone 22'],
  'Buryatia S.S.R.': [
    'Manchuria',
    'Sea Zone 60',
    'Sea Zone 61',
    'Sea Zone 62',
    'Soviet Far East',
    'Yakut S.S.R.',
  ],
  'Caroline Islands': ['Sea Zone 50'],
  Caucasus: ['Kazakh S.S.R.', 'Persia', 'Russia', 'Sea Zone 16', 'Ukraine S.S.R.', 'West Russia'],
  'Central United States': [
    'Eastern United States',
    'Mexico',
    'Western Canada',
    'Western United States',
  ],
  China: ['French Indochina', 'Kwangtung', 'Manchuria', 'Sinkiang'],
  'East Indies': ['Sea Zone 37'],
  'Eastern Canada': [
    'Eastern United States',
    'Sea Zone 1',
    'Sea Zone 10',
    'Sea Zone 9',
    'Western Canada',
  ],
  'Eastern Europe': [
    'Balkans',
    'Belorussia',
    'Germany',
    'Karelia S.S.R.',
    'Sea Zone 5',
    'Ukraine S.S.R.',
  ],
  'Eastern United States': [
    'Central United States',
    'Eastern Canada',
    'Panama',
    'Sea Zone 10',
    'Sea Zone 9',
  ],
  'Evenki National Okrug': ['Novosibirsk', 'Russia', 'Yakut S.S.R.'],
  'French Equatorial Africa': [
    'Anglo-Egypt',
    'Belgian Congo',
    'French West Africa',
    'Sea Zone 17',
    'Sea Zone 23',
  ],
  'French Indochina': [
    'China',
    'India',
    'Kwangtung',
    'Sea Zone 35',
    'Sea Zone 36',
    'Sea Zone 37',
    'Sea Zone 59',
  ],
  'French Madagascar': ['Sea Zone 28', 'Sea Zone 29', 'Sea Zone 32', 'Sea Zone 33'],
  'French West Africa': ['French Equatorial Africa', 'Sea Zone 17', 'Sea Zone 23'],
  Germany: ['Balkans', 'Eastern Europe', 'Sea Zone 5', 'Southern Europe', 'Western Europe'],
  Gibraltar: ['Sea Zone 13'],
  Greenland: ['Sea Zone 2'],
  'Hawaiian Islands': ['Sea Zone 52'],
  India: ['French Indochina', 'Persia', 'Sea Zone 34', 'Sea Zone 35', 'Sea Zone 36'],
  'Italian East Africa': ['Anglo-Egypt', 'Belgian Congo', 'Rhodesia', 'Sea Zone 33', 'Sea Zone 34'],
  Japan: ['Sea Zone 60', 'Sea Zone 61'],
  'Karelia S.S.R.': [
    'Archangel',
    'Belorussia',
    'Eastern Europe',
    'Norway',
    'Sea Zone 3',
    'Sea Zone 4',
    'Sea Zone 5',
    'West Russia',
  ],
  'Kazakh S.S.R.': ['Caucasus', 'Novosibirsk', 'Persia', 'Russia', 'Sinkiang'],
  Kwangtung: ['China', 'French Indochina', 'Manchuria', 'Sea Zone 36', 'Sea Zone 59'],
  Libya: ['Algeria', 'Anglo-Egypt', 'Sea Zone 13', 'Sea Zone 14', 'Sea Zone 15'],
  Manchuria: ['Buryatia S.S.R.', 'China', 'Kwangtung', 'Sea Zone 59', 'Sea Zone 60', 'Sea Zone 61'],
  Mexico: ['Central United States', 'Panama', 'Sea Zone 54', 'Western United States'],
  'Midway Island': ['Sea Zone 56'],
  'New Guinea': ['Sea Zone 47'],
  'New Zealand': ['Sea Zone 41', 'Sea Zone 45'],
  Norway: ['Karelia S.S.R.', 'Sea Zone 3', 'Sea Zone 5', 'Sea Zone 6', 'Western Europe'],
  Novosibirsk: ['Evenki National Okrug', 'Kazakh S.S.R.', 'Russia', 'Sinkiang', 'Yakut S.S.R.'],
  Okinawa: ['Sea Zone 58'],
  Panama: ['Eastern United States', 'Mexico', 'Sea Zone 10', 'Sea Zone 19', 'Sea Zone 20'],
  Persia: ['Caucasus', 'India', 'Kazakh S.S.R.', 'Sea Zone 34', 'Sea Zone 35', 'Trans-Jordan'],
  'Philippine Islands': ['Sea Zone 49'],
  Rhodesia: [
    'Belgian Congo',
    'Italian East Africa',
    'Sea Zone 33',
    'Sea Zone 34',
    'Union of South Africa',
  ],
  Russia: [
    'Archangel',
    'Caucasus',
    'Evenki National Okrug',
    'Kazakh S.S.R.',
    'Novosibirsk',
    'West Russia',
  ],
  'Sea Zone 1': ['Eastern Canada', 'Sea Zone 2', 'Sea Zone 8', 'Sea Zone 9'],
  'Sea Zone 10': [
    'Eastern Canada',
    'Eastern United States',
    'Panama',
    'Sea Zone 11',
    'Sea Zone 19',
    'Sea Zone 9',
  ],
  'Sea Zone 11': ['Sea Zone 10', 'Sea Zone 12', 'Sea Zone 18', 'Sea Zone 19', 'Sea Zone 9'],
  'Sea Zone 12': [
    'Algeria',
    'Sea Zone 11',
    'Sea Zone 13',
    'Sea Zone 17',
    'Sea Zone 18',
    'Sea Zone 8',
    'Sea Zone 9',
  ],
  'Sea Zone 13': [
    'Algeria',
    'Gibraltar',
    'Libya',
    'Sea Zone 12',
    'Sea Zone 14',
    'Southern Europe',
    'Western Europe',
  ],
  'Sea Zone 14': [
    'Algeria',
    'Anglo-Egypt',
    'Libya',
    'Sea Zone 13',
    'Sea Zone 15',
    'Sea Zone 16',
    'Southern Europe',
    'Western Europe',
  ],
  'Sea Zone 15': [
    'Anglo-Egypt',
    'Libya',
    'Sea Zone 14',
    'Sea Zone 16',
    'Sea Zone 34',
    'Trans-Jordan',
  ],
  'Sea Zone 16': ['Balkans', 'Caucasus', 'Sea Zone 14', 'Sea Zone 15', 'Ukraine S.S.R.'],
  'Sea Zone 17': [
    'French Equatorial Africa',
    'French West Africa',
    'Sea Zone 12',
    'Sea Zone 18',
    'Sea Zone 22',
    'Sea Zone 23',
  ],
  'Sea Zone 18': [
    'Brazil',
    'Sea Zone 11',
    'Sea Zone 12',
    'Sea Zone 17',
    'Sea Zone 19',
    'Sea Zone 22',
  ],
  'Sea Zone 19': [
    'Panama',
    'Sea Zone 10',
    'Sea Zone 11',
    'Sea Zone 18',
    'Sea Zone 20',
    'West Indies',
  ],
  'Sea Zone 2': [
    'Greenland',
    'Sea Zone 1',
    'Sea Zone 3',
    'Sea Zone 7',
    'Sea Zone 8',
    'United Kingdom',
  ],
  'Sea Zone 20': ['Panama', 'Sea Zone 19', 'Sea Zone 21', 'Sea Zone 54'],
  'Sea Zone 21': ['Sea Zone 20', 'Sea Zone 25', 'Sea Zone 43'],
  'Sea Zone 22': [
    'Brazil',
    'Sea Zone 17',
    'Sea Zone 18',
    'Sea Zone 23',
    'Sea Zone 24',
    'Sea Zone 25',
  ],
  'Sea Zone 23': [
    'Belgian Congo',
    'French Equatorial Africa',
    'French West Africa',
    'Sea Zone 17',
    'Sea Zone 22',
    'Sea Zone 24',
    'Sea Zone 27',
  ],
  'Sea Zone 24': ['Sea Zone 22', 'Sea Zone 23', 'Sea Zone 25', 'Sea Zone 26', 'Sea Zone 27'],
  'Sea Zone 25': ['Sea Zone 21', 'Sea Zone 22', 'Sea Zone 24', 'Sea Zone 26', 'Sea Zone 42'],
  'Sea Zone 26': ['Sea Zone 24', 'Sea Zone 25', 'Sea Zone 27'],
  'Sea Zone 27': [
    'Sea Zone 23',
    'Sea Zone 24',
    'Sea Zone 26',
    'Sea Zone 28',
    'Union of South Africa',
  ],
  'Sea Zone 28': [
    'French Madagascar',
    'Sea Zone 27',
    'Sea Zone 29',
    'Sea Zone 33',
    'Union of South Africa',
  ],
  'Sea Zone 29': ['French Madagascar', 'Sea Zone 28', 'Sea Zone 30', 'Sea Zone 32'],
  'Sea Zone 3': [
    'Karelia S.S.R.',
    'Norway',
    'Sea Zone 2',
    'Sea Zone 4',
    'Sea Zone 6',
    'United Kingdom',
  ],
  'Sea Zone 30': ['Sea Zone 29', 'Sea Zone 31', 'Sea Zone 32', 'Sea Zone 38', 'Sea Zone 39'],
  'Sea Zone 31': ['Sea Zone 30', 'Sea Zone 32', 'Sea Zone 35', 'Sea Zone 37', 'Sea Zone 38'],
  'Sea Zone 32': [
    'French Madagascar',
    'Sea Zone 29',
    'Sea Zone 30',
    'Sea Zone 31',
    'Sea Zone 33',
    'Sea Zone 34',
    'Sea Zone 35',
  ],
  'Sea Zone 33': [
    'French Madagascar',
    'Italian East Africa',
    'Rhodesia',
    'Sea Zone 28',
    'Sea Zone 32',
    'Sea Zone 34',
  ],
  'Sea Zone 34': [
    'Anglo-Egypt',
    'India',
    'Italian East Africa',
    'Persia',
    'Rhodesia',
    'Sea Zone 15',
    'Sea Zone 32',
    'Sea Zone 33',
    'Sea Zone 35',
    'Trans-Jordan',
  ],
  'Sea Zone 35': [
    'French Indochina',
    'India',
    'Persia',
    'Sea Zone 31',
    'Sea Zone 32',
    'Sea Zone 34',
    'Sea Zone 36',
    'Sea Zone 37',
  ],
  'Sea Zone 36': [
    'French Indochina',
    'India',
    'Kwangtung',
    'Sea Zone 35',
    'Sea Zone 37',
    'Sea Zone 48',
    'Sea Zone 49',
    'Sea Zone 59',
  ],
  'Sea Zone 37': [
    'East Indies',
    'French Indochina',
    'Sea Zone 31',
    'Sea Zone 35',
    'Sea Zone 36',
    'Sea Zone 38',
    'Sea Zone 47',
    'Sea Zone 48',
  ],
  'Sea Zone 38': [
    'Australia',
    'Sea Zone 30',
    'Sea Zone 31',
    'Sea Zone 37',
    'Sea Zone 39',
    'Sea Zone 46',
    'Sea Zone 47',
  ],
  'Sea Zone 39': ['Australia', 'Sea Zone 30', 'Sea Zone 38', 'Sea Zone 40'],
  'Sea Zone 4': ['Archangel', 'Karelia S.S.R.', 'Sea Zone 3'],
  'Sea Zone 40': ['Australia', 'Sea Zone 39', 'Sea Zone 41', 'Sea Zone 46'],
  'Sea Zone 41': [
    'New Zealand',
    'Sea Zone 40',
    'Sea Zone 42',
    'Sea Zone 44',
    'Sea Zone 45',
    'Sea Zone 46',
  ],
  'Sea Zone 42': ['Sea Zone 25', 'Sea Zone 41', 'Sea Zone 43', 'Sea Zone 44'],
  'Sea Zone 43': ['Sea Zone 21', 'Sea Zone 42', 'Sea Zone 44', 'Sea Zone 53', 'Sea Zone 54'],
  'Sea Zone 44': [
    'Sea Zone 41',
    'Sea Zone 42',
    'Sea Zone 43',
    'Sea Zone 45',
    'Sea Zone 52',
    'Sea Zone 53',
  ],
  'Sea Zone 45': [
    'New Zealand',
    'Sea Zone 41',
    'Sea Zone 44',
    'Sea Zone 46',
    'Sea Zone 47',
    'Sea Zone 50',
    'Sea Zone 51',
    'Sea Zone 52',
    'Solomon Islands',
  ],
  'Sea Zone 46': [
    'Australia',
    'Sea Zone 38',
    'Sea Zone 40',
    'Sea Zone 41',
    'Sea Zone 45',
    'Sea Zone 47',
  ],
  'Sea Zone 47': [
    'New Guinea',
    'Sea Zone 37',
    'Sea Zone 38',
    'Sea Zone 45',
    'Sea Zone 46',
    'Sea Zone 48',
    'Sea Zone 50',
  ],
  'Sea Zone 48': [
    'Borneo',
    'Sea Zone 36',
    'Sea Zone 37',
    'Sea Zone 47',
    'Sea Zone 49',
    'Sea Zone 50',
  ],
  'Sea Zone 49': [
    'Philippine Islands',
    'Sea Zone 36',
    'Sea Zone 48',
    'Sea Zone 50',
    'Sea Zone 58',
    'Sea Zone 59',
    'Sea Zone 60',
  ],
  'Sea Zone 5': [
    'Eastern Europe',
    'Germany',
    'Karelia S.S.R.',
    'Norway',
    'Sea Zone 6',
    'Western Europe',
  ],
  'Sea Zone 50': [
    'Caroline Islands',
    'Sea Zone 45',
    'Sea Zone 47',
    'Sea Zone 48',
    'Sea Zone 49',
    'Sea Zone 51',
    'Sea Zone 58',
  ],
  'Sea Zone 51': [
    'Sea Zone 45',
    'Sea Zone 50',
    'Sea Zone 52',
    'Sea Zone 57',
    'Sea Zone 58',
    'Sea Zone 60',
    'Wake Island',
  ],
  'Sea Zone 52': [
    'Hawaiian Islands',
    'Sea Zone 44',
    'Sea Zone 45',
    'Sea Zone 51',
    'Sea Zone 53',
    'Sea Zone 55',
    'Sea Zone 56',
    'Sea Zone 57',
  ],
  'Sea Zone 53': ['Sea Zone 43', 'Sea Zone 44', 'Sea Zone 52', 'Sea Zone 54', 'Sea Zone 55'],
  'Sea Zone 54': [
    'Mexico',
    'Sea Zone 20',
    'Sea Zone 43',
    'Sea Zone 53',
    'Sea Zone 55',
    'Western United States',
  ],
  'Sea Zone 55': [
    'Sea Zone 52',
    'Sea Zone 53',
    'Sea Zone 54',
    'Sea Zone 56',
    'Sea Zone 64',
    'Western Canada',
    'Western United States',
  ],
  'Sea Zone 56': [
    'Midway Island',
    'Sea Zone 52',
    'Sea Zone 55',
    'Sea Zone 57',
    'Sea Zone 63',
    'Sea Zone 64',
  ],
  'Sea Zone 57': [
    'Sea Zone 51',
    'Sea Zone 52',
    'Sea Zone 56',
    'Sea Zone 60',
    'Sea Zone 62',
    'Sea Zone 63',
  ],
  'Sea Zone 58': ['Okinawa', 'Sea Zone 49', 'Sea Zone 50', 'Sea Zone 51', 'Sea Zone 60'],
  'Sea Zone 59': [
    'French Indochina',
    'Kwangtung',
    'Manchuria',
    'Sea Zone 36',
    'Sea Zone 49',
    'Sea Zone 60',
    'Sea Zone 61',
  ],
  'Sea Zone 6': [
    'Norway',
    'Sea Zone 3',
    'Sea Zone 5',
    'Sea Zone 7',
    'United Kingdom',
    'Western Europe',
  ],
  'Sea Zone 60': [
    'Buryatia S.S.R.',
    'Japan',
    'Manchuria',
    'Sea Zone 49',
    'Sea Zone 51',
    'Sea Zone 57',
    'Sea Zone 58',
    'Sea Zone 59',
    'Sea Zone 61',
    'Sea Zone 62',
  ],
  'Sea Zone 61': ['Buryatia S.S.R.', 'Japan', 'Manchuria', 'Sea Zone 59', 'Sea Zone 60'],
  'Sea Zone 62': [
    'Buryatia S.S.R.',
    'Sea Zone 57',
    'Sea Zone 60',
    'Sea Zone 63',
    'Soviet Far East',
  ],
  'Sea Zone 63': [
    'Alaska',
    'Sea Zone 56',
    'Sea Zone 57',
    'Sea Zone 62',
    'Sea Zone 64',
    'Western Canada',
  ],
  'Sea Zone 64': ['Alaska', 'Sea Zone 55', 'Sea Zone 56', 'Sea Zone 63', 'Western Canada'],
  'Sea Zone 7': ['Sea Zone 2', 'Sea Zone 6', 'Sea Zone 8', 'United Kingdom', 'Western Europe'],
  'Sea Zone 8': [
    'Sea Zone 1',
    'Sea Zone 12',
    'Sea Zone 2',
    'Sea Zone 7',
    'Sea Zone 9',
    'United Kingdom',
  ],
  'Sea Zone 9': [
    'Eastern Canada',
    'Eastern United States',
    'Sea Zone 1',
    'Sea Zone 10',
    'Sea Zone 11',
    'Sea Zone 12',
    'Sea Zone 8',
  ],
  Sinkiang: ['China', 'Kazakh S.S.R.', 'Novosibirsk'],
  'Solomon Islands': ['Sea Zone 45'],
  'Southern Europe': ['Balkans', 'Germany', 'Sea Zone 13', 'Sea Zone 14', 'Western Europe'],
  'Soviet Far East': ['Buryatia S.S.R.', 'Sea Zone 62', 'Yakut S.S.R.'],
  'Trans-Jordan': ['Anglo-Egypt', 'Persia', 'Sea Zone 15', 'Sea Zone 34'],
  'Ukraine S.S.R.': [
    'Balkans',
    'Belorussia',
    'Caucasus',
    'Eastern Europe',
    'Sea Zone 16',
    'West Russia',
  ],
  'Union of South Africa': ['Rhodesia', 'Sea Zone 27', 'Sea Zone 28'],
  'United Kingdom': ['Sea Zone 2', 'Sea Zone 3', 'Sea Zone 6', 'Sea Zone 7', 'Sea Zone 8'],
  'Wake Island': ['Sea Zone 51'],
  'West Indies': ['Sea Zone 19'],
  'West Russia': [
    'Archangel',
    'Belorussia',
    'Caucasus',
    'Karelia S.S.R.',
    'Russia',
    'Ukraine S.S.R.',
  ],
  'Western Canada': [
    'Alaska',
    'Central United States',
    'Eastern Canada',
    'Sea Zone 55',
    'Sea Zone 63',
    'Sea Zone 64',
    'Western United States',
  ],
  'Western Europe': [
    'Germany',
    'Norway',
    'Sea Zone 13',
    'Sea Zone 14',
    'Sea Zone 5',
    'Sea Zone 6',
    'Sea Zone 7',
    'Southern Europe',
  ],
  'Western United States': [
    'Central United States',
    'Mexico',
    'Sea Zone 54',
    'Sea Zone 55',
    'Western Canada',
  ],
  'Yakut S.S.R.': ['Buryatia S.S.R.', 'Evenki National Okrug', 'Novosibirsk', 'Soviet Far East'],
};

export const SPECIAL_ADJACENCIES: Record<string, SpecialAdjacency> = {
  'Sea Zone 15|Sea Zone 34': {
    kind: 'canal',
    territories: ['Sea Zone 15', 'Sea Zone 34'],
    requiredTerritories: ['Anglo-Egypt', 'Trans-Jordan'],
  },
  'Sea Zone 20|Sea Zone 54': {
    kind: 'canal',
    territories: ['Sea Zone 20', 'Sea Zone 54'],
    requiredTerritories: ['Panama'],
  },
};
