import type { TerritoryName } from './territory-names';

export type TerritoryKind = 'land' | 'sea';
export type TerritorySubKind = 'coastal' | 'interior' | 'island';

export interface TerritoryInfo {
  readonly kind: TerritoryKind;
  readonly subKind: TerritorySubKind;
}

export const TERRITORY_INFO_BY_NAME: Record<TerritoryName, TerritoryInfo> = {
  Alaska: { kind: 'land', subKind: 'coastal' },
  Algeria: { kind: 'land', subKind: 'coastal' },
  'Anglo-Egypt': { kind: 'land', subKind: 'coastal' },
  Archangel: { kind: 'land', subKind: 'coastal' },
  Australia: { kind: 'land', subKind: 'coastal' },
  Balkans: { kind: 'land', subKind: 'coastal' },
  'Belgian Congo': { kind: 'land', subKind: 'coastal' },
  Belorussia: { kind: 'land', subKind: 'interior' },
  Borneo: { kind: 'land', subKind: 'coastal' },
  Brazil: { kind: 'land', subKind: 'coastal' },
  'Buryatia S.S.R.': { kind: 'land', subKind: 'coastal' },
  'Caroline Islands': { kind: 'land', subKind: 'island' },
  Caucasus: { kind: 'land', subKind: 'coastal' },
  'Central United States': { kind: 'land', subKind: 'interior' },
  China: { kind: 'land', subKind: 'interior' },
  'East Indies': { kind: 'land', subKind: 'coastal' },
  'Eastern Canada': { kind: 'land', subKind: 'coastal' },
  'Eastern Europe': { kind: 'land', subKind: 'coastal' },
  'Eastern United States': { kind: 'land', subKind: 'coastal' },
  'Evenki National Okrug': { kind: 'land', subKind: 'interior' },
  'French Equatorial Africa': { kind: 'land', subKind: 'coastal' },
  'French Indochina': { kind: 'land', subKind: 'coastal' },
  'French Madagascar': { kind: 'land', subKind: 'coastal' },
  'French West Africa': { kind: 'land', subKind: 'coastal' },
  Germany: { kind: 'land', subKind: 'coastal' },
  Gibraltar: { kind: 'land', subKind: 'coastal' },
  Greenland: { kind: 'land', subKind: 'coastal' },
  'Hawaiian Islands': { kind: 'land', subKind: 'island' },
  India: { kind: 'land', subKind: 'coastal' },
  'Italian East Africa': { kind: 'land', subKind: 'coastal' },
  Japan: { kind: 'land', subKind: 'coastal' },
  'Karelia S.S.R.': { kind: 'land', subKind: 'coastal' },
  'Kazakh S.S.R.': { kind: 'land', subKind: 'interior' },
  Kwangtung: { kind: 'land', subKind: 'coastal' },
  Libya: { kind: 'land', subKind: 'coastal' },
  Manchuria: { kind: 'land', subKind: 'coastal' },
  Mexico: { kind: 'land', subKind: 'coastal' },
  'Midway Island': { kind: 'land', subKind: 'island' },
  'New Guinea': { kind: 'land', subKind: 'island' },
  'New Zealand': { kind: 'land', subKind: 'coastal' },
  Norway: { kind: 'land', subKind: 'coastal' },
  Novosibirsk: { kind: 'land', subKind: 'interior' },
  Okinawa: { kind: 'land', subKind: 'island' },
  Panama: { kind: 'land', subKind: 'coastal' },
  Persia: { kind: 'land', subKind: 'coastal' },
  'Philippine Islands': { kind: 'land', subKind: 'island' },
  Rhodesia: { kind: 'land', subKind: 'coastal' },
  Russia: { kind: 'land', subKind: 'interior' },
  'Sea Zone 1': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 10': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 11': { kind: 'sea', subKind: 'interior' },
  'Sea Zone 12': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 13': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 14': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 15': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 16': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 17': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 18': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 19': { kind: 'sea', subKind: 'island' },
  'Sea Zone 2': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 20': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 21': { kind: 'sea', subKind: 'interior' },
  'Sea Zone 22': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 23': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 24': { kind: 'sea', subKind: 'interior' },
  'Sea Zone 25': { kind: 'sea', subKind: 'interior' },
  'Sea Zone 26': { kind: 'sea', subKind: 'interior' },
  'Sea Zone 27': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 28': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 29': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 3': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 30': { kind: 'sea', subKind: 'interior' },
  'Sea Zone 31': { kind: 'sea', subKind: 'interior' },
  'Sea Zone 32': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 33': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 34': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 35': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 36': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 37': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 38': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 39': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 4': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 40': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 41': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 42': { kind: 'sea', subKind: 'interior' },
  'Sea Zone 43': { kind: 'sea', subKind: 'interior' },
  'Sea Zone 44': { kind: 'sea', subKind: 'interior' },
  'Sea Zone 45': { kind: 'sea', subKind: 'island' },
  'Sea Zone 46': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 47': { kind: 'sea', subKind: 'island' },
  'Sea Zone 48': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 49': { kind: 'sea', subKind: 'island' },
  'Sea Zone 5': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 50': { kind: 'sea', subKind: 'island' },
  'Sea Zone 51': { kind: 'sea', subKind: 'island' },
  'Sea Zone 52': { kind: 'sea', subKind: 'island' },
  'Sea Zone 53': { kind: 'sea', subKind: 'interior' },
  'Sea Zone 54': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 55': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 56': { kind: 'sea', subKind: 'island' },
  'Sea Zone 57': { kind: 'sea', subKind: 'interior' },
  'Sea Zone 58': { kind: 'sea', subKind: 'island' },
  'Sea Zone 59': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 6': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 60': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 61': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 62': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 63': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 64': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 7': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 8': { kind: 'sea', subKind: 'coastal' },
  'Sea Zone 9': { kind: 'sea', subKind: 'coastal' },
  Sinkiang: { kind: 'land', subKind: 'interior' },
  'Solomon Islands': { kind: 'land', subKind: 'island' },
  'Southern Europe': { kind: 'land', subKind: 'coastal' },
  'Soviet Far East': { kind: 'land', subKind: 'coastal' },
  'Trans-Jordan': { kind: 'land', subKind: 'coastal' },
  'Ukraine S.S.R.': { kind: 'land', subKind: 'coastal' },
  'Union of South Africa': { kind: 'land', subKind: 'coastal' },
  'United Kingdom': { kind: 'land', subKind: 'coastal' },
  'Wake Island': { kind: 'land', subKind: 'island' },
  'West Indies': { kind: 'land', subKind: 'island' },
  'West Russia': { kind: 'land', subKind: 'interior' },
  'Western Canada': { kind: 'land', subKind: 'coastal' },
  'Western Europe': { kind: 'land', subKind: 'coastal' },
  'Western United States': { kind: 'land', subKind: 'coastal' },
  'Yakut S.S.R.': { kind: 'land', subKind: 'interior' },
};
