export const LAND_TERRITORY_NAMES = [
  "Alaska",
  "Algeria",
  "Anglo-Egypt",
  "Archangel",
  "Australia",
  "Balkans",
  "Belgian Congo",
  "Belorussia",
  "Borneo",
  "Brazil",
  "Buryatia S.S.R.",
  "Caroline Islands",
  "Caucasus",
  "Central United States",
  "China",
  "East Indies",
  "Eastern Canada",
  "Eastern Europe",
  "Eastern United States",
  "Evenki National Okrug",
  "French Equatorial Africa",
  "French Indochina",
  "French Madagascar",
  "French West Africa",
  "Germany",
  "Gibraltar",
  "Greenland",
  "Hawaiian Islands",
  "India",
  "Italian East Africa",
  "Japan",
  "Karelia S.S.R.",
  "Kazakh S.S.R.",
  "Kwangtung",
  "Libya",
  "Manchuria",
  "Mexico",
  "Midway Island",
  "New Guinea",
  "New Zealand",
  "Norway",
  "Novosibirsk",
  "Okinawa",
  "Panama",
  "Persia",
  "Philippine Islands",
  "Rhodesia",
  "Russia",
  "Sinkiang",
  "Solomon Islands",
  "Southern Europe",
  "Soviet Far East",
  "Trans-Jordan",
  "Ukraine S.S.R.",
  "Union of South Africa",
  "United Kingdom",
  "Wake Island",
  "West Indies",
  "West Russia",
  "Western Canada",
  "Western Europe",
  "Western United States",
  "Yakut S.S.R.",
] as const;

export const SEA_TERRITORY_NAMES = [
  "Sea Zone 1",
  "Sea Zone 10",
  "Sea Zone 11",
  "Sea Zone 12",
  "Sea Zone 13",
  "Sea Zone 14",
  "Sea Zone 15",
  "Sea Zone 16",
  "Sea Zone 17",
  "Sea Zone 18",
  "Sea Zone 19",
  "Sea Zone 2",
  "Sea Zone 20",
  "Sea Zone 21",
  "Sea Zone 22",
  "Sea Zone 23",
  "Sea Zone 24",
  "Sea Zone 25",
  "Sea Zone 26",
  "Sea Zone 27",
  "Sea Zone 28",
  "Sea Zone 29",
  "Sea Zone 3",
  "Sea Zone 30",
  "Sea Zone 31",
  "Sea Zone 32",
  "Sea Zone 33",
  "Sea Zone 34",
  "Sea Zone 35",
  "Sea Zone 36",
  "Sea Zone 37",
  "Sea Zone 38",
  "Sea Zone 39",
  "Sea Zone 4",
  "Sea Zone 40",
  "Sea Zone 41",
  "Sea Zone 42",
  "Sea Zone 43",
  "Sea Zone 44",
  "Sea Zone 45",
  "Sea Zone 46",
  "Sea Zone 47",
  "Sea Zone 48",
  "Sea Zone 49",
  "Sea Zone 5",
  "Sea Zone 50",
  "Sea Zone 51",
  "Sea Zone 52",
  "Sea Zone 53",
  "Sea Zone 54",
  "Sea Zone 55",
  "Sea Zone 56",
  "Sea Zone 57",
  "Sea Zone 58",
  "Sea Zone 59",
  "Sea Zone 6",
  "Sea Zone 60",
  "Sea Zone 61",
  "Sea Zone 62",
  "Sea Zone 63",
  "Sea Zone 64",
  "Sea Zone 7",
  "Sea Zone 8",
  "Sea Zone 9",
] as const;

export const TERRITORY_NAMES = [
  "Alaska",
  "Algeria",
  "Anglo-Egypt",
  "Archangel",
  "Australia",
  "Balkans",
  "Belgian Congo",
  "Belorussia",
  "Borneo",
  "Brazil",
  "Buryatia S.S.R.",
  "Caroline Islands",
  "Caucasus",
  "Central United States",
  "China",
  "East Indies",
  "Eastern Canada",
  "Eastern Europe",
  "Eastern United States",
  "Evenki National Okrug",
  "French Equatorial Africa",
  "French Indochina",
  "French Madagascar",
  "French West Africa",
  "Germany",
  "Gibraltar",
  "Greenland",
  "Hawaiian Islands",
  "India",
  "Italian East Africa",
  "Japan",
  "Karelia S.S.R.",
  "Kazakh S.S.R.",
  "Kwangtung",
  "Libya",
  "Manchuria",
  "Mexico",
  "Midway Island",
  "New Guinea",
  "New Zealand",
  "Norway",
  "Novosibirsk",
  "Okinawa",
  "Panama",
  "Persia",
  "Philippine Islands",
  "Rhodesia",
  "Russia",
  "Sea Zone 1",
  "Sea Zone 10",
  "Sea Zone 11",
  "Sea Zone 12",
  "Sea Zone 13",
  "Sea Zone 14",
  "Sea Zone 15",
  "Sea Zone 16",
  "Sea Zone 17",
  "Sea Zone 18",
  "Sea Zone 19",
  "Sea Zone 2",
  "Sea Zone 20",
  "Sea Zone 21",
  "Sea Zone 22",
  "Sea Zone 23",
  "Sea Zone 24",
  "Sea Zone 25",
  "Sea Zone 26",
  "Sea Zone 27",
  "Sea Zone 28",
  "Sea Zone 29",
  "Sea Zone 3",
  "Sea Zone 30",
  "Sea Zone 31",
  "Sea Zone 32",
  "Sea Zone 33",
  "Sea Zone 34",
  "Sea Zone 35",
  "Sea Zone 36",
  "Sea Zone 37",
  "Sea Zone 38",
  "Sea Zone 39",
  "Sea Zone 4",
  "Sea Zone 40",
  "Sea Zone 41",
  "Sea Zone 42",
  "Sea Zone 43",
  "Sea Zone 44",
  "Sea Zone 45",
  "Sea Zone 46",
  "Sea Zone 47",
  "Sea Zone 48",
  "Sea Zone 49",
  "Sea Zone 5",
  "Sea Zone 50",
  "Sea Zone 51",
  "Sea Zone 52",
  "Sea Zone 53",
  "Sea Zone 54",
  "Sea Zone 55",
  "Sea Zone 56",
  "Sea Zone 57",
  "Sea Zone 58",
  "Sea Zone 59",
  "Sea Zone 6",
  "Sea Zone 60",
  "Sea Zone 61",
  "Sea Zone 62",
  "Sea Zone 63",
  "Sea Zone 64",
  "Sea Zone 7",
  "Sea Zone 8",
  "Sea Zone 9",
  "Sinkiang",
  "Solomon Islands",
  "Southern Europe",
  "Soviet Far East",
  "Trans-Jordan",
  "Ukraine S.S.R.",
  "Union of South Africa",
  "United Kingdom",
  "Wake Island",
  "West Indies",
  "West Russia",
  "Western Canada",
  "Western Europe",
  "Western United States",
  "Yakut S.S.R.",
] as const;

export type LandTerritoryName = (typeof LAND_TERRITORY_NAMES)[number];
export type SeaTerritoryName = (typeof SEA_TERRITORY_NAMES)[number];
export type TerritoryName = (typeof TERRITORY_NAMES)[number];
